version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendence

  pgadmin:
    depends_on:
      - postgres
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - transcendence

  nestjs:
    restart: on-failure
    depends_on:
      - postgres
    build: 
      context: backend/
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/workspace
    env_file:
      - .env
    container_name: nestjs
    networks:
      - transcendence

  frontend:
    env_file:
      - .env
    container_name: frontend
    restart: on-failure
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
    networks:
      - transcendence

volumes:
  db-data:
    driver: local
  nest_volume:
    driver: local
    name: nestjs
    driver_opts:
      type: none
      device: ./backend
      o: bind

networks:
  transcendence:
    driver: bridge
    name: transcendence_network

